In [1]:
import torch
import numpy as np

# Create Tensor - ver1

In [2]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

### question
- You should transform numpy arrays to PyTorch tensors with torch.from_numpy. Otherwise some weird issues might occur. img = torch.from_numpy(img).float().to(device) 

In [3]:
torch.tensor(np.array([[1, 2], [3, 4]]))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [4]:
torch.from_numpy(np.array([[1, 2], [3, 4]]))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

# Change dtype

In [5]:
torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [6]:
torch.from_numpy(np.array([[1, 2], [3, 4]])).type(torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

# Change Device

In [7]:
if torch.cuda.is_available():
    device = torch.device('cuda')

In [8]:
torch.tensor([[1, 2], [3, 4]], device=device)

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [9]:
torch.tensor([[1, 2], [3, 4]]).to(device)

tensor([[1, 2],
        [3, 4]], device='cuda:0')

# Create Tensor - ver2

In [10]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [12]:
torch.full((2, 2), fill_value=2)

tensor([[2., 2.],
        [2., 2.]])

# Create Tensor - ver3

In [13]:
target = ((1, 2, 3), (4, 5, 6))
target_one = torch.tensor(target, dtype=torch.float64)

In [14]:
target_one.new_zeros(4, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [15]:
target_two = torch.tensor(target, device=device)

In [16]:
target_two.new_full((4, 2), fill_value=5)

tensor([[5, 5],
        [5, 5],
        [5, 5],
        [5, 5]], device='cuda:0')

# Create Tensor - ver4

In [17]:
torch.zeros_like(target_one)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [18]:
torch.ones_like(target_two)

tensor([[1, 1, 1],
        [1, 1, 1]], device='cuda:0')

In [19]:
torch.full_like(target_two, fill_value=3)

tensor([[3, 3, 3],
        [3, 3, 3]], device='cuda:0')